### ISSUE TITLE
Not showing in plugin menu

### ISSUE THREAD

**Issue by thischrisoliver** [pavelkuligin/chart#1]
After installing the plugin, it doesn't show in the plugin menu or the preferences window for me. I'm running Sketch 48.1.

**Comment by pavelkuligin** [comment]
@thischrisoliver It is really strange... You can Install Chart with sketchpacks: https://sketchpacks.com/pavelkuligin/chart

**Comment by GOBsNotOnBoard** [comment]
I normally install plugins via Sketch Runner, but since Chart wasn't listed in Runner for installation, I tried installing manually.

I just tried again, and there were two plugin files inside the zip file: Chart.sketchplugin and chArt-1.sketchplugin. If I double-click Chart.sketchplugin, it doesn't show in the menu. If I double-click chArt-1.sketchplugin, it shows in the menu, but only Line chart, Stacked area chart, and Sparkline are in the menu, and none of them work.

Since manual installation still isn't working, I installed Sketchpacks and then Chart via Sketchpacks, and now it's working perfectly fine.

**Comment by JetPack33** [comment]
I am having the same issue, running 48.2

**Comment by pavelkuligin** [comment]
@JetPack33 How did you install Chart? Please, describe your workflow.

**Comment by JetPack33** [comment]
Hi!
Download zip folder > opened > double clicked on the file titled Chart.sketchplugin.
Checked Sketch, plugin did not show up in the Plugin dropdown list or Manage Plugins... 

I have tested other plugins using the same installation method. So far this has been the only plugin I am having issues with using this installation method.

**Comment by pavelkuligin** [comment]
@JetPack33 Can you download ZIP now and try to install Chart again?
And one more thing, can you send me list of files in extracted ZIP?
There must be:
appcast.xml
Chart.sketchplugin
[folder] images
LICENSE
Readme.md

**Comment by JetPack33** [comment]
It worked :)  Thank you!
