### ISSUE TITLE
Can't generate some charts in sketch 52.5 chart 4.6.0

### ISSUE THREAD

**Issue by jz-nbme** [pavelkuligin/chart#37]
I purchased chart plugin and I follow the instructions on the repo to for example to generate a pie chart:
Pie Chart, Donut Chart — categories: 1, items: 5 (categories count should be equal to canvases count);
I select one canvas(circle) and enter 1 and 5 and I only get 1 piece of the pie chart?
I can produce a bar chart but all the bars are the same color  and same for most of the others.

Now that you are charging for the plugin you may consider improving your instructions. Thank you.

**Comment by pavelkuligin** [comment]
@jz-nbme can you send me a screenshot of SetParams popup? It seems to me that your color palette has only one color.

**Comment by jz-nbme** [comment]
![screenshot 2018-12-03 10 25 16](https://user-images.githubusercontent.com/28399204/49383020-c94cd700-f6e5-11e8-97f5-001583e97781.png)

**Comment by pavelkuligin** [comment]
@jz-nbme the problem here with a number of items. You have 4 colors in your palette but you want to generate a pie chart with 5 slices. You should add more colors to the palette.
Regarding the bar chart, all bars will have the same color. You can try to create a bar chart with categories: 2 and items: 10, for example.

**Comment by jz-nbme** [comment]
Yes that seems to be working now, thanks.
