### ISSUE TITLE
Crashed on Macbook Pro M1

### ISSUE THREAD

**Issue by andrewtsuei** [pavelkuligin/chart#59]
Crashed on Sketch 70.3 with Macbook Pro M1

**Comment by pavelkuligin** [comment]
Hey @andrewtsuei! It is known issue, but we cannot fix it on our side because problem in the one of main component that provided by Sketch dev team. We have two workarounds at this moment: https://support.invisionapp.com/hc/en-us/community/posts/360074793811-Craft-Sketch-plugin-not-working-on-new-Apple-Silicon-M1-

Sorry about that...
